[2022-08-12 03:19:29,128] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: elasticsearch_dag.connections_to_es manual__2022-08-12T03:19:27.346423+00:00 [queued]>
[2022-08-12 03:19:29,138] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: elasticsearch_dag.connections_to_es manual__2022-08-12T03:19:27.346423+00:00 [queued]>
[2022-08-12 03:19:29,139] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 03:19:29,139] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-12 03:19:29,140] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 03:19:29,153] {taskinstance.py:1377} INFO - Executing <Task(PostgresToElasticOperator): connections_to_es> on 2022-08-12 03:19:27.346423+00:00
[2022-08-12 03:19:29,160] {standard_task_runner.py:52} INFO - Started process 1062 to run task
[2022-08-12 03:19:29,164] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'elasticsearch_dag', 'connections_to_es', 'manual__2022-08-12T03:19:27.346423+00:00', '--job-id', '381', '--raw', '--subdir', 'DAGS_FOLDER/elastic_dag.py', '--cfg-path', '/tmp/tmposlhfit9', '--error-file', '/tmp/tmptp8431s7']
[2022-08-12 03:19:29,166] {standard_task_runner.py:80} INFO - Job 381: Subtask connections_to_es
[2022-08-12 03:19:29,232] {task_command.py:369} INFO - Running <TaskInstance: elasticsearch_dag.connections_to_es manual__2022-08-12T03:19:27.346423+00:00 [running]> on host a1c9528fe5e1
[2022-08-12 03:19:29,307] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=elasticsearch_dag
AIRFLOW_CTX_TASK_ID=connections_to_es
AIRFLOW_CTX_EXECUTION_DATE=2022-08-12T03:19:27.346423+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-12T03:19:27.346423+00:00
[2022-08-12 03:19:29,321] {base.py:68} INFO - Using connection ID 'elasticsearch_default' for task execution.
[2022-08-12 03:19:29,330] {base.py:68} INFO - Using connection ID '***_default' for task execution.
[2022-08-12 03:19:29,335] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/operators/postgres_to_elastic.py", line 23, in execute
    with closing(pg.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 113, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "***" (172.26.0.4), port 5432 failed: FATAL:  password authentication failed for user "***"

[2022-08-12 03:19:29,346] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=elasticsearch_dag, task_id=connections_to_es, execution_date=20220812T031927, start_date=20220812T031929, end_date=20220812T031929
[2022-08-12 03:19:29,356] {standard_task_runner.py:97} ERROR - Failed to execute job 381 for task connections_to_es (connection to server at "***" (172.26.0.4), port 5432 failed: FATAL:  password authentication failed for user "***"
; 1062)
[2022-08-12 03:19:29,383] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-12 03:19:29,414] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
