[2022-07-31 00:05:37,639] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule_dag.task_2 scheduled__2022-07-30T00:00:00+00:00 [queued]>
[2022-07-31 00:05:37,676] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule_dag.task_2 scheduled__2022-07-30T00:00:00+00:00 [queued]>
[2022-07-31 00:05:37,679] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-31 00:05:37,680] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-31 00:05:37,681] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-31 00:05:37,725] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): task_2> on 2022-07-30 00:00:00+00:00
[2022-07-31 00:05:37,739] {standard_task_runner.py:52} INFO - Started process 17009 to run task
[2022-07-31 00:05:37,751] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_rule_dag', 'task_2', 'scheduled__2022-07-30T00:00:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule_dag.py', '--cfg-path', '/tmp/tmph3hl2pn1', '--error-file', '/tmp/tmpsxx9dmv5']
[2022-07-31 00:05:37,754] {standard_task_runner.py:80} INFO - Job 266: Subtask task_2
[2022-07-31 00:05:37,934] {task_command.py:369} INFO - Running <TaskInstance: trigger_rule_dag.task_2 scheduled__2022-07-30T00:00:00+00:00 [running]> on host 2525a2c6e2b8
[2022-07-31 00:05:38,112] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_rule_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-07-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-30T00:00:00+00:00
[2022-07-31 00:05:38,116] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-31 00:05:38,119] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'exit 1']
[2022-07-31 00:05:38,135] {subprocess.py:85} INFO - Output:
[2022-07-31 00:05:38,149] {subprocess.py:96} INFO - Command exited with return code 1
[2022-07-31 00:05:38,217] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-07-31 00:05:38,252] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=trigger_rule_dag, task_id=task_2, execution_date=20220730T000000, start_date=20220731T000537, end_date=20220731T000538
[2022-07-31 00:05:38,308] {standard_task_runner.py:97} ERROR - Failed to execute job 266 for task task_2 (Bash command failed. The command returned a non-zero exit code 1.; 17009)
[2022-07-31 00:05:38,360] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-31 00:05:38,445] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
