[2022-08-19 00:21:03,129] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: docker_dag.docker_command manual__2022-08-19T00:15:54.178667+00:00 [queued]>
[2022-08-19 00:21:03,143] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: docker_dag.docker_command manual__2022-08-19T00:15:54.178667+00:00 [queued]>
[2022-08-19 00:21:03,144] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 00:21:03,145] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-08-19 00:21:03,146] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 00:21:03,164] {taskinstance.py:1377} INFO - Executing <Task(DockerOperator): docker_command> on 2022-08-19 00:15:54.178667+00:00
[2022-08-19 00:21:03,171] {standard_task_runner.py:52} INFO - Started process 720 to run task
[2022-08-19 00:21:03,177] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'docker_dag', 'docker_command', 'manual__2022-08-19T00:15:54.178667+00:00', '--job-id', '587', '--raw', '--subdir', 'DAGS_FOLDER/docker_dag.py', '--cfg-path', '/tmp/tmprmvzha8v', '--error-file', '/tmp/tmpurkqco0z']
[2022-08-19 00:21:03,179] {standard_task_runner.py:80} INFO - Job 587: Subtask docker_command
[2022-08-19 00:21:03,261] {task_command.py:369} INFO - Running <TaskInstance: docker_dag.docker_command manual__2022-08-19T00:15:54.178667+00:00 [running]> on host 50aef51b862a
[2022-08-19 00:21:03,350] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=docker_dag
AIRFLOW_CTX_TASK_ID=docker_command
AIRFLOW_CTX_EXECUTION_DATE=2022-08-19T00:15:54.178667+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-19T00:15:54.178667+00:00
[2022-08-19 00:21:03,388] {docker.py:247} INFO - Starting docker container from image bobrik/socat
[2022-08-19 00:21:03,408] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://docker-proxy:2375/v1.41/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 387, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 254, in _run_image
    return self._run_image_with_mounts(self.mounts + [tmp_mount], add_tmp_variable=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 298, in _run_image_with_mounts
    tty=self.tty,
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/container.py", line 428, in create_container
    return self.create_container_from_config(config, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/container.py", line 439, in create_container_from_config
    return self._result(res, True)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error for http://docker-proxy:2375/v1.41/containers/create: Internal Server Error ("json: cannot unmarshal string into Go struct field HostConfig.HostConfig.Mounts of type mount.Mount")
[2022-08-19 00:21:03,422] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=docker_dag, task_id=docker_command, execution_date=20220819T001554, start_date=20220819T002103, end_date=20220819T002103
[2022-08-19 00:21:03,436] {standard_task_runner.py:97} ERROR - Failed to execute job 587 for task docker_command (500 Server Error for http://docker-proxy:2375/v1.41/containers/create: Internal Server Error ("json: cannot unmarshal string into Go struct field HostConfig.HostConfig.Mounts of type mount.Mount"); 720)
[2022-08-19 00:21:03,470] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-19 00:21:03,536] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
