[2022-10-27 02:55:29,876] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spark_job_dag.docker_command manual__2022-10-27T02:48:14.329786+00:00 [queued]>
[2022-10-27 02:55:29,891] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spark_job_dag.docker_command manual__2022-10-27T02:48:14.329786+00:00 [queued]>
[2022-10-27 02:55:29,892] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-27 02:55:29,893] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-10-27 02:55:29,893] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-27 02:55:29,913] {taskinstance.py:1377} INFO - Executing <Task(DockerOperator): docker_command> on 2022-10-27 02:48:14.329786+00:00
[2022-10-27 02:55:29,922] {standard_task_runner.py:52} INFO - Started process 66 to run task
[2022-10-27 02:55:29,929] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'spark_job_dag', 'docker_command', 'manual__2022-10-27T02:48:14.329786+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/spark_job_dag.py', '--cfg-path', '/tmp/tmpjl0908bh', '--error-file', '/tmp/tmp3cx6gwso']
[2022-10-27 02:55:29,932] {standard_task_runner.py:80} INFO - Job 72: Subtask docker_command
[2022-10-27 02:55:30,130] {task_command.py:369} INFO - Running <TaskInstance: spark_job_dag.docker_command manual__2022-10-27T02:48:14.329786+00:00 [running]> on host 7a39bdd9f452
[2022-10-27 02:55:30,250] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_job_dag
AIRFLOW_CTX_TASK_ID=docker_command
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T02:48:14.329786+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-27T02:48:14.329786+00:00
[2022-10-27 02:55:30,271] {docker.py:371} INFO - Pulling docker image bde2020/spark-master:latest
[2022-10-27 02:55:32,405] {docker.py:385} INFO - latest: Pulling from bde2020/spark-master
[2022-10-27 02:55:32,408] {docker.py:385} INFO - 396c31837116: Pulling fs layer
[2022-10-27 02:55:32,408] {docker.py:385} INFO - bb59ba756ca3: Pulling fs layer
[2022-10-27 02:55:32,409] {docker.py:385} INFO - 52d9f65633a2: Pulling fs layer
[2022-10-27 02:55:32,410] {docker.py:385} INFO - 7cdbc775d228: Pulling fs layer
[2022-10-27 02:55:32,410] {docker.py:385} INFO - 1832b9aadd75: Pulling fs layer
[2022-10-27 02:55:32,411] {docker.py:385} INFO - 4f4fb700ef54: Pulling fs layer
[2022-10-27 02:55:32,412] {docker.py:385} INFO - 616308593c75: Pulling fs layer
[2022-10-27 02:55:32,413] {docker.py:385} INFO - 7cdbc775d228: Waiting
[2022-10-27 02:55:32,413] {docker.py:385} INFO - 1832b9aadd75: Waiting
[2022-10-27 02:55:32,414] {docker.py:385} INFO - 616308593c75: Waiting
[2022-10-27 02:55:32,415] {docker.py:385} INFO - 4f4fb700ef54: Waiting
[2022-10-27 02:55:33,200] {docker.py:385} INFO - 396c31837116: Downloading
[2022-10-27 02:55:33,201] {docker.py:385} INFO - bb59ba756ca3: Downloading
[2022-10-27 02:55:33,203] {docker.py:385} INFO - bb59ba756ca3: Verifying Checksum
[2022-10-27 02:55:33,204] {docker.py:385} INFO - bb59ba756ca3: Download complete
[2022-10-27 02:55:33,205] {docker.py:385} INFO - 52d9f65633a2: Downloading
[2022-10-27 02:55:33,206] {docker.py:385} INFO - 52d9f65633a2: Verifying Checksum
[2022-10-27 02:55:33,208] {docker.py:385} INFO - 52d9f65633a2: Download complete
[2022-10-27 02:55:34,374] {docker.py:385} INFO - 396c31837116: Download complete
[2022-10-27 02:55:34,376] {docker.py:385} INFO - 396c31837116: Extracting
[2022-10-27 02:55:34,558] {docker.py:385} INFO - 7cdbc775d228: Downloading
[2022-10-27 02:55:34,559] {docker.py:385} INFO - 7cdbc775d228: Verifying Checksum
[2022-10-27 02:55:34,559] {docker.py:385} INFO - 7cdbc775d228: Download complete
[2022-10-27 02:55:34,561] {docker.py:385} INFO - 1832b9aadd75: Downloading
[2022-10-27 02:55:34,562] {docker.py:385} INFO - 396c31837116: Pull complete
[2022-10-27 02:55:34,563] {docker.py:385} INFO - bb59ba756ca3: Extracting
[2022-10-27 02:55:34,838] {docker.py:385} INFO - bb59ba756ca3: Pull complete
[2022-10-27 02:55:34,842] {docker.py:385} INFO - 52d9f65633a2: Extracting
[2022-10-27 02:55:34,843] {docker.py:385} INFO - 52d9f65633a2: Pull complete
[2022-10-27 02:55:34,845] {docker.py:385} INFO - 7cdbc775d228: Extracting
[2022-10-27 02:55:35,065] {docker.py:385} INFO - 7cdbc775d228: Pull complete
[2022-10-27 02:55:35,269] {docker.py:385} INFO - 4f4fb700ef54: Downloading
[2022-10-27 02:55:35,269] {docker.py:385} INFO - 4f4fb700ef54: Download complete
[2022-10-27 02:55:35,501] {docker.py:385} INFO - 616308593c75: Downloading
[2022-10-27 02:55:35,501] {docker.py:385} INFO - 616308593c75: Verifying Checksum
[2022-10-27 02:55:35,502] {docker.py:385} INFO - 616308593c75: Download complete
[2022-10-27 02:55:48,165] {docker.py:385} INFO - 1832b9aadd75: Download complete
[2022-10-27 02:55:48,460] {docker.py:385} INFO - 1832b9aadd75: Extracting
[2022-10-27 02:55:59,410] {docker.py:385} INFO - 1832b9aadd75: Pull complete
[2022-10-27 02:55:59,411] {docker.py:385} INFO - 4f4fb700ef54: Extracting
[2022-10-27 02:55:59,412] {docker.py:385} INFO - 4f4fb700ef54: Pull complete
[2022-10-27 02:55:59,413] {docker.py:385} INFO - 616308593c75: Extracting
[2022-10-27 02:55:59,414] {docker.py:385} INFO - 616308593c75: Pull complete
[2022-10-27 02:55:59,419] {docker.py:380} INFO - Digest: sha256:3fe3e2c13a3d1f889b5e6127851b56734c3dbd0c268699e5fd3273631973c418
[2022-10-27 02:55:59,419] {docker.py:380} INFO - Status: Downloaded newer image for bde2020/spark-master:latest
[2022-10-27 02:55:59,420] {docker.py:247} INFO - Starting docker container from image bde2020/spark-master:latest
[2022-10-27 02:55:59,479] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-socket-proxy:2375/v1.37/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 387, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 254, in _run_image
    return self._run_image_with_mounts(self.mounts + [tmp_mount], add_tmp_variable=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 298, in _run_image_with_mounts
    tty=self.tty,
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/container.py", line 428, in create_container
    return self.create_container_from_config(config, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/container.py", line 439, in create_container_from_config
    return self._result(res, True)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error for http://docker-socket-proxy:2375/v1.37/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /home/airflow/simple-app")
[2022-10-27 02:55:59,505] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=spark_job_dag, task_id=docker_command, execution_date=20221027T024814, start_date=20221027T025529, end_date=20221027T025559
[2022-10-27 02:55:59,537] {standard_task_runner.py:97} ERROR - Failed to execute job 72 for task docker_command (400 Client Error for http://docker-socket-proxy:2375/v1.37/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /home/airflow/simple-app"); 66)
[2022-10-27 02:55:59,562] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-27 02:55:59,612] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
