[2022-07-28 12:59:14,557] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule_dag.task_1 manual__2022-07-28T12:59:13.999839+00:00 [queued]>
[2022-07-28 12:59:14,567] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule_dag.task_1 manual__2022-07-28T12:59:13.999839+00:00 [queued]>
[2022-07-28 12:59:14,567] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 12:59:14,568] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-28 12:59:14,569] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 12:59:14,582] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): task_1> on 2022-07-28 12:59:13.999839+00:00
[2022-07-28 12:59:14,587] {standard_task_runner.py:52} INFO - Started process 1537 to run task
[2022-07-28 12:59:14,591] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_rule_dag', 'task_1', 'manual__2022-07-28T12:59:13.999839+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule_dag.py', '--cfg-path', '/tmp/tmphl0vykyf', '--error-file', '/tmp/tmpp1vr6lda']
[2022-07-28 12:59:14,592] {standard_task_runner.py:80} INFO - Job 226: Subtask task_1
[2022-07-28 12:59:14,659] {task_command.py:369} INFO - Running <TaskInstance: trigger_rule_dag.task_1 manual__2022-07-28T12:59:13.999839+00:00 [running]> on host 2525a2c6e2b8
[2022-07-28 12:59:14,748] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_rule_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-28T12:59:13.999839+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-28T12:59:13.999839+00:00
[2022-07-28 12:59:14,749] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-28 12:59:14,750] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'exit 1']
[2022-07-28 12:59:14,761] {subprocess.py:85} INFO - Output:
[2022-07-28 12:59:14,764] {subprocess.py:96} INFO - Command exited with return code 1
[2022-07-28 12:59:14,778] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-07-28 12:59:14,783] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=trigger_rule_dag, task_id=task_1, execution_date=20220728T125913, start_date=20220728T125914, end_date=20220728T125914
[2022-07-28 12:59:14,796] {standard_task_runner.py:97} ERROR - Failed to execute job 226 for task task_1 (Bash command failed. The command returned a non-zero exit code 1.; 1537)
[2022-07-28 12:59:14,845] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-28 12:59:14,879] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
