[2022-08-05 00:03:50,441] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule_dag.task_2 scheduled__2022-08-04T00:00:00+00:00 [queued]>
[2022-08-05 00:03:50,539] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule_dag.task_2 scheduled__2022-08-04T00:00:00+00:00 [queued]>
[2022-08-05 00:03:50,544] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-05 00:03:50,548] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-05 00:03:50,549] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-05 00:03:50,667] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): task_2> on 2022-08-04 00:00:00+00:00
[2022-08-05 00:03:50,678] {standard_task_runner.py:52} INFO - Started process 74 to run task
[2022-08-05 00:03:50,682] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_rule_dag', 'task_2', 'scheduled__2022-08-04T00:00:00+00:00', '--job-id', '309', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule_dag.py', '--cfg-path', '/tmp/tmp3mkqtzvu', '--error-file', '/tmp/tmpcswb22w_']
[2022-08-05 00:03:50,684] {standard_task_runner.py:80} INFO - Job 309: Subtask task_2
[2022-08-05 00:03:50,797] {task_command.py:369} INFO - Running <TaskInstance: trigger_rule_dag.task_2 scheduled__2022-08-04T00:00:00+00:00 [running]> on host 531c07ae0142
[2022-08-05 00:03:50,962] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_rule_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-08-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-04T00:00:00+00:00
[2022-08-05 00:03:50,966] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-05 00:03:50,967] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'exit 1']
[2022-08-05 00:03:50,986] {subprocess.py:85} INFO - Output:
[2022-08-05 00:03:50,989] {subprocess.py:96} INFO - Command exited with return code 1
[2022-08-05 00:03:51,018] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-08-05 00:03:51,025] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=trigger_rule_dag, task_id=task_2, execution_date=20220804T000000, start_date=20220805T000350, end_date=20220805T000351
[2022-08-05 00:03:51,042] {standard_task_runner.py:97} ERROR - Failed to execute job 309 for task task_2 (Bash command failed. The command returned a non-zero exit code 1.; 74)
[2022-08-05 00:03:51,063] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-05 00:03:51,107] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
